export const COLUMN_HEADER = [
    {name: '№', size: 44},
    {name: 'Имя сотрудника', size: 206, src: true},
    {name: 'ID номер', size: 97},
    {name: 'Телефона', size: 107},
    {name: 'Пол', size: 87, src: true},
    {name: 'Дата рождения', size: 113},
    {name: 'Метро', size: 121, src: true},
    {name: 'Адрес проживания', size: 183},
    {name: 'Банк', size: 121, src: true},
    {name: 'Номер карта', size: 137},
    {name: 'Гражданство', size: 118, src: true},
    {name: 'Паспорт', size: 105},
    {name: 'Кем выдан', size: 184},
    {name: 'Срок действия', size: 113},
    {name: 'Место рождения', size: 117},
    {name: 'Адрес прописки', size: 183},
    {name: 'Патент', size: 113, src: true},
    {name: 'Срок действия', size: 113},
    {name: 'СНИЛС', size: 137},
    {name: 'ИНН', size: 137},
    {name: 'Мед. книжка', size: 137},
    {name: 'Должность', size: 137, src: true},
    {name: 'Подразделение', size: 137, src: true},
    {name: 'Решение', size: 121, src: true},
    {name: 'Источник', size: 137},
    {name: 'Дата', size: 114},
    {name: 'Примечание', size: 203},

]